services:
  telegram-listener:
    build: .
    container_name: telegram-listener
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./telegram_session.session:/app/telegram_session.session
    depends_on:
      - upload-server

  upload-server:
    build: ./upload_server
    container_name: upload-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./upload_server_data:/app/uploads
      - ./upload_server_db:/app/db

